# Setup
title:        Denis's notebook
tagline:      the one who does not write notes is doomed to write them multiple times
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Denis Besic
  url:        http://denza.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-tactile